on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Tests
        uses: Yandex-Practicum/test-project-action@latest
        with:
          project: 'slozhno-sosredotochitsya'
