on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_SKIP_DOWNLOAD: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Tests
        uses: rpill/test-projects-yp@main
        with:
          project: 'asd'
